require("issacnewtown.remaps")
require("issacnewtown.set")
require("issacnewtown.lazy")
require("issacnewtown.autocmd")
require("issacnewtown.compile")
require("issacnewtown.statusline")

-- return {
--     'nvim-lualine/lualine.nvim',
--     config = function()
--         local blank = {
--             function() return "      " end
--         }
--
--         local diagnostics = {
--             'diagnostics',
--             sources = { 'nvim_diagnostic' },
--             sections = { 'error', 'warn', 'hint' },
--             symbols = { error = 'E:', warn = 'W:', info = 'G:', hint = 'H:' },
--             colored = false,
--             update_in_insert = true,
--             always_visible = true,
--         }
--
--         require('lualine').setup {
--             options = {
--                 icons_enabled = false,
--                 theme = 'auto',
--                 component_separators = { left = '', right = ''},
--                 section_separators = { left = '', right = ''},
--                 disabled_filetypes = {
--                     statusline = {},
--                     winbar = {},
--                 },
--                 ignore_focus = {},
--                 always_divide_middle = true,
--                 always_show_tabline = true,
--                 globalstatus = false,
--                 refresh = {
--                     statusline = 1000,
--                     tabline = 1000,
--                     winbar = 1000,
--                     refresh_time = 16, -- ~60fps
--                     events = {
--                         'WinEnter',
--                         'BufEnter',
--                         'BufWritePost',
--                         'SessionLoadPost',
--                         'FileChangedShellPost',
--                         'VimResized',
--                         'Filetype',
--                         'CursorMoved',
--                         'CursorMovedI',
--                         'ModeChanged',
--                     },
--                 }
--             },
--             sections = {
--                 lualine_a = {},
--                 lualine_b = {},
--                 lualine_c = {{'filename', path = 1}},
--                 lualine_x = {'location', blank, 'progress'},
--                 lualine_y = {},
--                 lualine_z = {}
--             },
--             inactive_sections = {
--                 lualine_a = {},
--                 lualine_b = {},
--                 lualine_c = {{'filename', path = 1}},
--                 lualine_x = {'location', blank, 'progress'},
--                 lualine_y = {},
--                 lualine_z = {}
--             },
--             tabline = {},
--             winbar = {},
--             inactive_winbar = {},
--             extensions = {}
--         }
--
--         vim.keymap.set("n", "<leader>cc", function()
--             local colorscheme = vim.g.colors_name
--
--             if colorscheme ~= "kanagawa" then
--                 print("your colorscheme is kanagawa")
--             end
--         end)
--     end
-- }

