return {
  -- "obsidian-nvim/obsidian.nvim",
  -- version = "*",
  -- lazy = true,
  -- ft = "markdown",
  --
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  -- },
  --
  -- opts = {
  --   workspaces = {
  --     {
  --       name = "personal",
  --       path = "~/dev/secondbrain",
  --     },
  --   },
  -- },
  --
  -- config = function()
  --     vim.opt.conceallevel = 1
  -- end
}
